#### Two Layer Neural  Network 

##### Training

In [9]:
import numpy as np
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
 
    return 1/(1+np.exp(-x))

X = np.array([[0,0,0],
              [0,0,1],
              [0,1,1],
              [0,1,0],
              [1,1,0],
              [1,1,1],
              [1,0,1],
              [1,0,0]
              ])
 
y = np.array([[0,0,1,0,1,1,1,0]]).T
 
np.random.seed(1)
 
# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((3,4)) - 1 #3 layer0 input nodes ,4 mid layer nodes,1 output nodes
syn1 = 2*np.random.random((4,1)) - 1
 
for j in xrange(60000):
 
    # Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
 
    # how much did we miss the target value?
    l2_error = y - l2
 
 
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)
 
    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)
 
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)
 
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
print('\n Output')
print(l2)
print('\n First layer of weights')
print(syn0)
print('\n Second layer of weights')
print(syn1)


 Output
[[  1.52456337e-07]
 [  6.74991811e-03]
 [  9.93030237e-01]
 [  7.94584454e-03]
 [  9.94257349e-01]
 [  9.99971866e-01]
 [  9.94782188e-01]
 [  6.30124856e-03]]

 First layer of weights
[[ 0.61420144  5.8434963  -3.58201618 -0.68090924]
 [-2.47356539 -2.79146742 -1.42153945 -1.59435907]
 [-1.68096508  6.34404401  0.44953563  4.30798633]]

 Second layer of weights
[[-21.32945288]
 [  8.21954687]
 [-21.77496956]
 [  3.49207227]]


##### Test

In [10]:
def vote(X,syn0,syn1):
    l0= X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    print(l2)

In [14]:
vote([[1,0,1],[1,1,1],[1,0,0]],syn0,syn1)

[[ 0.99478224]
 [ 0.99997187]
 [ 0.00630119]]
